// Generated by CoffeeScript 1.6.2
(function() {
  var Lazy, argv, file, filename, fs, removeExtension, skipNewLine, _i, _len, _ref;

  fs = require('fs');

  Lazy = require('lazy');

  argv = (require('optimist')).argv;

  removeExtension = function(filename) {
    var i;

    i = filename.lastIndexOf('.');
    if (i < 0) {
      return '';
    } else {
      return filename.substring(0, i);
    }
  };

  _ref = argv._;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    filename = _ref[_i];
    skipNewLine = true;
    file = '';
    fs.writeFileSync("" + (removeExtension(filename)) + ".coffee", file);
    new Lazy(fs.createReadStream(filename, {
      encoding: 'utf8'
    })).lines.forEach(function(line) {
      line = String(line);
      if (line.indexOf('    ') === 0 || line.indexOf('\t') === 0) {
        fs.appendFileSync("" + (removeExtension(filename)) + ".coffee", line.substring(4) + '\n');
        return skipNewLine = false;
      } else {
        if (!skipNewLine) {
          fs.appendFileSync("" + (removeExtension(filename)) + ".coffee", '\n');
        }
        return skipNewLine = true;
      }
    });
  }

}).call(this);
